SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
SCRIPTS="$(dirname $SOURCE)/../scripts"
PYTHON="$(dirname $SOURCE)/../python"
TESTDEV="$(dirname $SOURCE)/../test/dev"
DIRS="$( cd -P $SCRIPTS && pwd )"
DIRP="$( cd -P $PYTHON && pwd )"
DIRD="$( cd -P $TESTDEV && pwd )"

export PATH="$DIRD:$DIRS:$PATH"
export PYTHONPATH="$DIRS:$PYTHONPATH"
echo "$DIRS added to PATH and PYTHONPATH"
export PYTHONPATH="$DIRP:$PYTHONPATH"
echo "$DIRP added to PATH"
export PYTHONPATH="$DIRD:$PYTHONPATH"
echo "$DIRD added to PATH"
